### ISSUE TITLE
No package named bandana found.

### ISSUE THREAD

**Issue by JulyZR** [mpes-kit/fuller#2]
When using fuller-generator-visualize, I met a Python package named bandana that I couldn't find.
Could you give me some suggestion?

**Comment by RealPolitiX** [comment]
It's this one (https://github.com/RealPolitiX/bandana), but it hasn't been updated for some time, so please beware of version-related issues.

**Comment by JulyZR** [comment]
Can I ask how the data in band_all_paths_cart.out.pbe, which is loaded using pbedata = fuller.utils.load_calculation(r'..\theory\band_all_paths_cart.out.pbe') in fuller/examples/01_Hexagonal_tiling.ipynb, was obtained? What do the data in that file represent?
